{{- if .Values.previewServer.backendConfig.enabled }}
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: ps-{{ include "google-tag-manager.fullname" . }}
  labels:
    {{- include "google-tag-manager.labels" . | nindent 4 }}
spec:
  {{- if hasKey .Values.previewServer.backendConfig "timeoutSec" }}
  timeoutSec: {{ .Values.previewServer.backendConfig.timeoutSec }}
  {{- end }}
  {{- with .Values.previewServer.backendConfig.healthCheck }}
  healthCheck:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.previewServer.backendConfig.securityPolicy }}
  securityPolicy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
