apiVersion: v1
kind: ConfigMap
metadata:
  name: ps-{{ include "google-tag-manager.fullname" . }}
  labels:
    {{- include "google-tag-manager.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.previewServer.environment | nindent 2 }}
