{{- $_ := set .Values.previewServer.secretEnvironment "CONTAINER_CONFIG" (b64enc .Values.containerConfig) }}
apiVersion: v1
kind: Secret
metadata:
  name: ps-{{ include "google-tag-manager.fullname" . }}
  labels:
    {{- include "google-tag-manager.labels" . | nindent 4 }}
type: Opaque
data:
  {{- toYaml .Values.previewServer.secretEnvironment | nindent 2 }}
