apiVersion: v1
kind: Service
metadata:
  name: ps-{{ include "google-tag-manager.fullname" . }}
  labels:
    {{- include "google-tag-manager.labels" . | nindent 4 }}
  {{- if or .Values.previewServer.service.neg.enabled .Values.previewServer.backendConfig.enabled }}
  annotations:
  {{- if .Values.previewServer.service.neg.enabled }}
    cloud.google.com/neg: '{"exposed_ports": {"{{ .Values.previewServer.service.port }}":{}}}'
  {{- end }}
  {{- if .Values.previewServer.backendConfig.enabled }}
    cloud.google.com/backend-config: '{"default": "ps-{{ include "google-tag-manager.fullname" . }}"}'
  {{- end }}
  {{- end }}
spec:
  type: {{ .Values.previewServer.service.type }}
  ports:
    - port: {{ .Values.previewServer.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/instance: preview-server
    {{- include "google-tag-manager.selectorLabels" . | nindent 4 }}
