{{- if .Values.serverSideTagging.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (printf "sst-%s" (include "google-tag-manager.fullname" .)) .Values.serverSideTagging.serviceAccount.name }}
  labels:
    {{- include "google-tag-manager.labels" . | nindent 4 }}
  {{- with .Values.serverSideTagging.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
